package com.ultikits.ultitools.context;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Collections;
import java.util.List;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import com.ultikits.testfixtures.finalviolation.validator.IllegalOverride;
import com.ultikits.testfixtures.finalviolation.validator.IllegalSubclass;
import com.ultikits.testfixtures.finalviolation.validator.OpenBase;
import com.ultikits.testfixtures.finalviolation.validator.SealedBase;
import com.ultikits.ultitools.aop.ProxyFactory;

@DisplayName("FinalContractValidator Tests")
class FinalContractValidatorTest {

    // SealedBase, OpenBase, IllegalSubclass and IllegalOverride are not nested here: they are
    // real, live @Final violations, and this test class lives in com.ultikits.ultitools.context -
    // a package other tests scan broadly (ComponentScannerTest, ContextConfigTest). A violation
    // compiled into this package would trip those unrelated scans for a reason that has nothing to
    // do with what they're testing. See com.ultikits.testfixtures.finalviolation.validator's
    // package-info for the full story (issue #190). LegalSubclass and Unrelated below never
    // violate anything, so they can stay colocated with the tests that use them as usual.

    public static class LegalSubclass extends OpenBase {
        @Override
        public void openMethod() { }
    }

    public static class Unrelated { }

    @Test
    @DisplayName("Should accept a class with no @Final ancestry")
    void shouldAcceptUnrelated() {
        assertTrue(FinalContractValidator.validate(Unrelated.class).isEmpty());
    }

    @Test
    @DisplayName("Should accept the @Final class itself")
    void shouldAcceptTheSealedClassItself() {
        assertTrue(FinalContractValidator.validate(SealedBase.class).isEmpty());
    }

    @Test
    @DisplayName("Should reject extending a @Final class")
    void shouldRejectExtendingSealedClass() {
        List<String> violations = FinalContractValidator.validate(IllegalSubclass.class);
        assertEquals(1, violations.size());
        assertTrue(violations.get(0).contains(IllegalSubclass.class.getName()), violations.get(0));
        assertTrue(violations.get(0).contains(SealedBase.class.getName()), violations.get(0));
    }

    @Test
    @DisplayName("Should accept overriding a method that is not @Final")
    void shouldAcceptOverridingOpenMethod() {
        assertTrue(FinalContractValidator.validate(LegalSubclass.class).isEmpty());
    }

    @Test
    @DisplayName("Should reject overriding a @Final method")
    void shouldRejectOverridingSealedMethod() {
        List<String> violations = FinalContractValidator.validate(IllegalOverride.class);
        assertEquals(1, violations.size());
        assertTrue(violations.get(0).contains("sealedMethod"), violations.get(0));
    }

    @Test
    @DisplayName("Should not flag a real ByteBuddy proxy generated over a @Final class")
    void shouldIgnoreRealGeneratedProxyOfSealedClass() {
        // A proxy of a @Final class is generated by the framework itself and is legitimate:
        // @Final constrains module authors, not the container. Exercise the ProxyFactory.
        // isProxyClass branch for real by generating an actual subclass through the same factory
        // the container uses: once AOP is wired (Task 11), the container proxies @Final beans
        // exactly like this, and the proxy class IS a direct subclass of the @Final type - the
        // same shape as IllegalSubclass above.
        ProxyFactory factory = new ProxyFactory(Collections.emptyList());
        Class<? extends SealedBase> proxyClass =
                factory.createProxyClass(SealedBase.class, Collections.emptySet());

        // Sanity check: confirm the fixture is actually what it claims to be before trusting the
        // validator's answer about it.
        assertTrue(ProxyFactory.isProxyClass(proxyClass),
                "fixture must be a real generated proxy for this test to mean anything");

        assertTrue(FinalContractValidator.validate(proxyClass).isEmpty());
    }
}
