# 是否使用其他的经济插件作为基础（即仅使用本插件的银行功能）
useThirdPartEconomy: false
# 是否开启利息
enableInterest: true
# 利率，利息 = 利率 × 本金
interestRate: 0.0003
# 利息发放间隔（分钟）
interestTime: 30

# 玩家初始货币数量
initial_money: 1000

# 货币名称
currency_name: '金币'
# 服务器管理员是否能够增减玩家货币
op_operate_money: false
# 是否开启服务器交易记录
server_trade_log: false
