package com.ultikits.ultitools.context;

import com.ultikits.ultitools.annotations.Final;
import com.ultikits.ultitools.aop.ProxyFactory;

import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;

/**
 * Enforces the {@link Final} contract when the framework loads a module's classes.
 * <p>
 * {@code @Final} replaces the {@code final} keyword for classes that also need AOP, so the JVM no
 * longer enforces it. This validator restores the constraint at class-loading time. Because the
 * framework loads every module, the check is effective across module boundaries, which a
 * compile-time annotation processor could not achieve.
 * <p>
 * <b>Known gaps.</b> The check is not compile-time, so an IDE will not flag a violation. Its
 * coverage is exactly the set of classes {@link ComponentScanner} walks: everything under a
 * module's declared {@code @UltiToolsModule(scanBasePackages)}. A class that ships in the same
 * module JAR but sits outside those declared packages is never scanned and therefore never
 * checked.
 * <p>
 * 该校验在类加载期恢复 {@code @Final} 的约束。框架加载全部模块，因此跨模块有效。
 * 但它不在编译期生效；覆盖范围严格等于组件扫描实际走到的类，即
 * {@code @UltiToolsModule(scanBasePackages)} 声明的包——声明包之外的类即使同在模块 JAR 中，
 * 也不会被扫描、因而不会被检查。
 *
 * @author wisdomme
 * @since 6.3.0
 */
public final class FinalContractValidator {

    private FinalContractValidator() {
        // Utility class
    }

    /**
     * Validates that the given class does not violate any {@code @Final} contract.
     *
     * @param clazz the class to validate
     * @return one description per violation, empty if the class is compliant
     */
    public static List<String> validate(Class<?> clazz) {
        List<String> violations = new ArrayList<>();
        if (clazz == null || clazz.isInterface() || clazz.isAnnotation() || clazz.isEnum()) {
            return violations;
        }
        // Proxies are generated by the container itself. @Final constrains module authors, not
        // the framework, so a proxy of a @Final class is legitimate.
        if (ProxyFactory.isProxyClass(clazz)) {
            return violations;
        }

        Class<?> superclass = clazz.getSuperclass();
        if (superclass != null && superclass.isAnnotationPresent(Final.class)) {
            violations.add(clazz.getName() + " extends " + superclass.getName()
                    + ", which is annotated @Final and must not be extended. "
                    + "Remove the 'extends' clause, or drop @Final from the parent if extension "
                    + "is intended.");
        }

        for (Method method : clazz.getDeclaredMethods()) {
            if (method.isSynthetic() || method.isBridge()) {
                continue;
            }
            Method overridden = findOverriddenSealedMethod(clazz, method);
            if (overridden != null) {
                violations.add(clazz.getName() + "#" + method.getName() + " overrides "
                        + overridden.getDeclaringClass().getName() + "#" + overridden.getName()
                        + ", which is annotated @Final and must not be overridden.");
            }
        }
        return violations;
    }

    /**
     * Walks up the hierarchy looking for a {@code @Final} method with the same signature.
     */
    private static Method findOverriddenSealedMethod(Class<?> clazz, Method method) {
        for (Class<?> current = clazz.getSuperclass();
             current != null && current != Object.class;
             current = current.getSuperclass()) {
            try {
                Method candidate = current.getDeclaredMethod(method.getName(),
                        method.getParameterTypes());
                if (candidate.isAnnotationPresent(Final.class)) {
                    return candidate;
                }
            } catch (NoSuchMethodException ignored) {
                // Not declared at this level; keep walking up.
            }
        }
        return null;
    }
}
