package com.ultikits.ultitools.context;

import com.ultikits.ultitools.annotations.Final;
import com.ultikits.ultitools.aop.ProxyFactory;
import com.ultikits.ultitools.utils.ReflectionUtil;

import org.jetbrains.annotations.ApiStatus;

import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Deque;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * Enforces the {@link Final} contract when the framework loads a module's classes.
 * <p>
 * {@code @Final} replaces the {@code final} keyword for classes that also need AOP, so the JVM no
 * longer enforces it. This validator restores the constraint at class-loading time. Because the
 * framework loads every module, the check is effective across module boundaries, which a
 * compile-time annotation processor could not achieve.
 * <p>
 * <b>Known gaps.</b> The check is not compile-time, so an IDE will not flag a violation. Its
 * coverage is exactly the set of classes {@link ComponentScanner} walks, and for a plugin module
 * that set comes from {@code PluginManager#getPluginScanPackages}'s three-level fallback: a
 * module's declared {@code @UltiToolsModule(scanBasePackages)}, else a {@code @ComponentScan} on
 * the plugin class, else the plugin class's own package. A module that declares neither annotation
 * is still checked - it falls back to its own package rather than dropping out of scanning
 * entirely. The framework's own classes are <b>not</b> checked in production: nothing ever invokes
 * {@link ComponentScanner} against {@code com.ultikits.ultitools} itself. {@code ContextConfig}
 * used to declare {@code @ComponentScan("com.ultikits.ultitools")} for exactly that purpose, but
 * the declaration was removed in 6.3.0 because the only thing that would have acted on it,
 * {@link SimpleContainer#processConfigurationClass(Class)}, had no caller anywhere in
 * {@code src/main} - it is invoked only from tests ({@code ContextConfigTest}, {@code ScanTest}).
 * A plugin module's class is unchecked if it sits outside whichever package that module's own scan
 * actually reaches; a framework class is unchecked unconditionally today.
 * <p>
 * The method-level check is transitive: it accumulates the chain of declarations that actually
 * override one another - per {@link ReflectionUtil#overrides(Method, Method)}, the single
 * implementation of JLS 8.4.8.1 this class shares with {@link ReflectionUtil#getAllMethods(Class)}
 * - rather than comparing {@code clazz}'s own declaration directly against each ancestor. A
 * widening override interposed between {@code clazz} and a {@code @Final} ancestor no longer
 * defeats the check, and the walk also follows implemented interfaces, not only the superclass
 * chain, so a {@code @Final} default method or a {@code @Final} interface is enforced too.
 * <p>
 * 该校验在类加载期恢复 {@code @Final} 的约束。框架加载全部模块，因此跨模块有效。
 * 但它不在编译期生效；覆盖范围严格等于组件扫描实际走到的类。对插件模块而言，这个范围来自
 * {@code PluginManager#getPluginScanPackages} 的三层回退：模块声明的
 * {@code @UltiToolsModule(scanBasePackages)}，其次插件类上的 {@code @ComponentScan}，都未声明
 * 则默认扫插件类自己所在的包——两个注解都不声明的模块依然会被检查，只是回退到自己的包，而不是
 * 完全跳出扫描。框架自身的类在生产环境中<b>不会</b>被检查：从未有代码对
 * {@code com.ultikits.ultitools} 自身发起过 {@link ComponentScanner} 扫描。{@code ContextConfig}
 * 曾经为此声明 {@code @ComponentScan("com.ultikits.ultitools")}，但唯一会处理这个声明的
 * {@link SimpleContainer#processConfigurationClass(Class)} 在 {@code src/main} 里没有任何调用方，
 * 该声明因此在 6.3.0 被移除——只有测试（{@code ContextConfigTest}、{@code ScanTest}）会调用它。
 * 对插件模块而言，类只要落在自己扫描实际到达的包之外就不受检查；而框架自身的类，目前无条件地
 * 不受检查。
 * <p>
 * 方法级检查具备传递性：通过 {@link ReflectionUtil#overrides(Method, Method)} 累积真正构成覆盖链的
 * 声明，而不是只拿 {@code clazz} 自身声明与每一层祖先直接比较；遍历同时沿接口向上走，因此
 * {@code @Final} 默认方法与 {@code @Final} 接口也在检查范围内。
 *
 * @author wisdomme
 * @since 6.3.0
 */
@ApiStatus.Internal
public final class FinalContractValidator {

    private static final Logger LOGGER = Logger.getLogger(FinalContractValidator.class.getName());

    private FinalContractValidator() {
        // Utility class
    }

    /**
     * Validates that the given class does not violate any {@code @Final} contract.
     *
     * @param clazz the class to validate
     * @return one description per violation, empty if the class is compliant
     */
    public static List<String> validate(Class<?> clazz) {
        List<String> violations = new ArrayList<>();
        if (clazz == null || clazz.isAnnotation() || clazz.isEnum()) {
            return violations;
        }
        // Proxies are generated by the container itself. @Final constrains module authors, not
        // the framework, so a proxy of a @Final class is legitimate. isProxyClass reads the
        // @ProxyOf marker ProxyFactory attaches at generation time - not a name pattern - so this
        // recognises a proxy directly rather than deriving anything itself. See ProxyFactory#unwrap
        // for the sibling call this validator does not need: it only asks "is this a proxy at
        // all", never "what did it proxy".
        if (ProxyFactory.isProxyClass(clazz)) {
            return violations;
        }

        Class<?> superclass = clazz.getSuperclass();
        if (superclass != null && superclass.isAnnotationPresent(Final.class)) {
            violations.add(clazz.getName() + " extends " + superclass.getName()
                    + ", which is annotated @Final and must not be extended. "
                    + "Remove the 'extends' clause, or drop @Final from the parent if extension "
                    + "is intended.");
        }

        // A @Final interface is rejected the same way a @Final superclass is - the only
        // difference is the relation word: two interfaces "extend" each other, a class
        // "implements" an interface. Modifier.isInterface(clazz.getModifiers()) decides which
        // applies; a class's getInterfaces() lists the interfaces it directly implements, an
        // interface's lists the interfaces it directly extends, so one loop covers both relations.
        boolean clazzIsInterface = Modifier.isInterface(clazz.getModifiers());
        String relation = clazzIsInterface ? "extends" : "implements";
        String participle = clazzIsInterface ? "extended" : "implemented";
        for (Class<?> iface : clazz.getInterfaces()) {
            if (iface.isAnnotationPresent(Final.class)) {
                violations.add(clazz.getName() + " " + relation + " " + iface.getName()
                        + ", which is annotated @Final and must not be " + participle + ". "
                        + "Remove the '" + relation + "' clause, or drop @Final from the "
                        + (clazzIsInterface ? "parent interface" : "interface")
                        + " if " + (clazzIsInterface ? "extension" : "implementation")
                        + " is intended.");
            }
        }

        // getDeclaredMethods() resolves every parameter and return type of every method it
        // returns, so a class whose signature references a type absent from its own defining
        // class loader throws NoClassDefFoundError right here - not a hypothetical: it is the
        // shape of a soft-dependency integration class (Vault, PlaceholderAPI, ...) with the
        // optional type in a method signature, including one disabled via @ConditionalOnConfig
        // because the dependency may not be installed. Before this method existed, nothing on
        // ComponentScanner's path touched method descriptors, so this check is what newly exposes
        // that class to the Error. Left uncaught, it escapes to ComponentScanner.scanDirectory's
        // production caller as an Error naming an unrelated missing class with no hint that a
        // @Final scan caused it, and ComponentScanner.scanJar catches NoClassDefFoundError and
        // simply skips the class - silently disabling this very check for it. Catching it here
        // instead keeps the check running (via the superclass-level findings already collected
        // above) and leaves a named trace instead of either outcome. See issue #190.
        try {
            for (Method method : clazz.getDeclaredMethods()) {
                if (method.isSynthetic() || method.isBridge()) {
                    continue;
                }
                Method overridden = findOverriddenSealedMethod(clazz, method);
                if (overridden != null) {
                    violations.add(clazz.getName() + "#" + method.getName() + " overrides "
                            + overridden.getDeclaringClass().getName() + "#" + overridden.getName()
                            + ", which is annotated @Final and must not be overridden.");
                }
            }
        } catch (NoClassDefFoundError | TypeNotPresentException e) {
            LOGGER.log(Level.WARNING, "cannot check @Final method contract for " + clazz.getName()
                    + ": " + e.getMessage() + " is not on the classpath", e);
        }
        return violations;
    }

    /**
     * Walks the hierarchy looking for a {@code @Final} method that {@code method} transitively
     * overrides, following both superclasses and implemented interfaces.
     * <p>
     * Matching on name and parameter types alone is not enough: a {@code private}, {@code static},
     * or cross-package package-private method in {@code clazz} that merely shares a signature with
     * an ancestor's {@code @Final} method is not an override at all per JLS 8.4.8.1, and reporting
     * it as one would reject a module that never actually did the thing {@code @Final} forbids.
     * Nor is it enough to compare a symmetric signature key: overriding is directional, so a key
     * comparison misses the mirror-image case - a subclass in the same package widening an
     * ancestor's package-private {@code @Final} method to {@code public}, which is a real override
     * and precisely what {@code @Final} exists to forbid.
     * <p>
     * {@link ReflectionUtil#overrides(Method, Method)} is the single implementation of that rule,
     * shared with {@link ReflectionUtil#getAllMethods(Class)}'s own override collapsing, so the two
     * checks agree by construction rather than by two people independently getting the same JLS
     * rule right. See issue #190.
     * <p>
     * The walk accumulates every declaration proven to be part of the override chain, starting
     * from {@code method} itself, and tests a newly-found candidate against <b>every</b> member of
     * that chain rather than only the most recently added one. A same-package widening override
     * interposed between {@code clazz} and a package-private {@code @Final} ancestor is exactly
     * the shape that requires this: comparing {@code method} directly against the {@code @Final}
     * declaration fails the package check, but comparing the widening override (already in the
     * chain because it was found first, one level up) against it succeeds, because that override
     * genuinely shares a package with the {@code @Final} declaration.
     * <p>
     * 按名称加参数类型匹配是不够的：{@code clazz} 中与祖先类的 {@code @Final} 方法签名相同的
     * {@code private}、{@code static} 或跨包包私有方法，根据 JLS 8.4.8.1 根本不构成重写。比较对称
     * 的签名 key 同样不够：覆盖是有方向的，key 比较会漏掉镜像的那一半——同包子类把祖先的包私有
     * {@code @Final} 方法放宽为 {@code public}，那是真正的覆盖，也正是 {@code @Final} 要禁止的。
     * 这里改用 {@link ReflectionUtil#overrides(Method, Method)}——该规则的唯一实现，与
     * {@link ReflectionUtil#getAllMethods(Class)} 共用，让两处检查天然一致。遍历会累积链条中已确认
     * 的每一条声明，新候选需要与链条中的<b>每一条</b>已有声明比较，而不只是最近加入的一条。
     */
    private static Method findOverriddenSealedMethod(Class<?> clazz, Method method) {
        List<Method> chain = new ArrayList<>();
        chain.add(method);
        Set<Class<?>> visited = new HashSet<>();
        Deque<Class<?>> toVisit = new ArrayDeque<>();
        enqueueSupertypes(clazz, toVisit);

        while (!toVisit.isEmpty()) {
            Class<?> current = toVisit.poll();
            if (current == null || current == Object.class || !visited.add(current)) {
                continue;
            }
            try {
                Method candidate = current.getDeclaredMethod(method.getName(),
                        method.getParameterTypes());
                boolean overridesChainMember = false;
                for (Method chained : chain) {
                    if (ReflectionUtil.overrides(chained, candidate)) {
                        overridesChainMember = true;
                        break;
                    }
                }
                if (overridesChainMember) {
                    chain.add(candidate);
                    if (candidate.isAnnotationPresent(Final.class)) {
                        return candidate;
                    }
                }
            } catch (NoSuchMethodException ignored) {
                // Not declared at this level; keep walking.
            }
            enqueueSupertypes(current, toVisit);
        }
        return null;
    }

    /**
     * Adds {@code from}'s direct superclass and directly implemented/extended interfaces to
     * {@code queue}, so a caller doing a breadth-first walk reaches a {@code @Final} method
     * declared on an interface of a superclass, not only one reachable through the superclass
     * chain alone.
     */
    private static void enqueueSupertypes(Class<?> from, Deque<Class<?>> queue) {
        Class<?> superclass = from.getSuperclass();
        if (superclass != null) {
            queue.add(superclass);
        }
        for (Class<?> iface : from.getInterfaces()) {
            queue.add(iface);
        }
    }
}
