datasource:
  type: "json"

language: "zh"

web-editor:
  enable: true
  port: 4567
  https:
    enable: false
    domain: ""
    keystore-file-path: ""
    keystore-password: ""
  trustIp: [ ]

account:
  username: ""
  password: ""
