# 是否启用治疗
enableHeal: true
# 是否启用白名单
enableWhitelist: false
# 是否启用回到上一个位置
enableBack: true
# 是否启用飞行
enableFly: true
# 是否启用切换模式
enableGmChange: true
# 是否启用随机传送
enableRandomTeleport: true
# 是否启用入服欢迎
enableJoinWelcome: true
# 是否启用TPA功能
enableTpa: true
# 是否启用速度设置功能
enableSpeed: true
# 是否启用封禁功能
enableBan: true
# 是否启用封禁功能
enableWarp: true
# 是否启用重生点设置
enableSpawn: true
# 是否启用Lore编辑器
enableLoreEditor: true
# 是否启用隐身功能
enableHide: true
# 是否启用玩家头顶显示功能
enableTitle: true
# 是否启用死亡惩罚功能
enableDeathPunishment: true
# 是否启用聊天功能
enableChat: true
# 是否启用@功能
enableAt: true
