# x秒后发送入服欢迎
sendMessageDelay: 4

# 入服欢迎语
welcome_message:
  - "&b欢迎加入服务器，&e%player_name%&b!"
  - "&b请友善对待他人，游戏愉快！"

# op入服提示语
op_join: "&c[管理员] &e%player_name% &c已上线"

# op下线提示语
op_quit: "&c[管理员] &e%player_name% &c已下线"

# 玩家入服提示语
player_join: "&c[玩家] &e%player_name% &c已上线"

# 玩家下线提示语
player_quit: "&c[玩家] &e%player_name% &c已下线"
