# 数据存储方式，内置json, sqlite和mysql，酌情更改，
# 每个存储方式之间的数据不是互通的，切换存储方式会导致数据丢失
# json: 可以手动更改内容，但是性能稳定性最低，崩溃下可能会丢失数据
# sqlite: 本地文件存储，性能稳定性较高，但是无法轻易手动更改数据
# mysql: 需要配置mysql数据库，性能稳定性最高，但是需要自行创建数据库
datasource:
  type: "sqlite"
  # 仅对json存储有效，数据自动保存时间（秒），高性能机器可酌情调低
  # 越低数据越不容易丢失，但是性能消耗越大
  # 越高性能消耗越小，但是数据丢失可能性越大
  flushRate: 10

# en for English, zh 为中文
language: "zh"

web-editor:
  enable: false

account:
  username: ""
  password: ""

mysql:
  enable: false
  host: localhost
  port: 3306
  username: root
  password: password
  database: ultitools
  connectionTimeout: 30000
  keepaliveTime: 60000
  maxLifetime: 1800000
  connectionTestQuery: "select 1"
  maximumPoolSize: 8
  cachePrepStmts: true
  prepStmtCacheSize: 250
  prepStmtCacheSqlLimit: 2048
