# 请按需修改前4行配置，后面的如果不懂请勿乱改
enable: false
host: localhost
port: 3306
username: root
password: password
database: ultitools
connectionTimeout: 30000
keepaliveTime: 60000
maxLifetime: 1800000
connectionTestQuery: "select 1"
maximumPoolSize: 8
cachePrepStmts: true
prepStmtCacheSize: 250
prepStmtCacheSqlLimit: 2048
