package com.ultikits.ultitools.aop;

import com.ultikits.ultitools.annotations.ExceptionCatch;
import com.ultikits.ultitools.annotations.Transactional;

import java.lang.annotation.Annotation;
import java.lang.reflect.Method;
import java.lang.reflect.Modifier;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * Decides whether a class can be proxied, and explains why not when it cannot.
 * <p>
 * Every rejection here becomes an explicit startup failure naming the class and method. None of
 * these cases may be skipped silently: a silently unproxied bean is exactly the failure mode that
 * left {@code @Transactional} inert since 6.2.0.
 * <p>
 * {@code private} and {@code static} methods are not a capability gap but a usage error. The JVM
 * dispatches them with {@code invokespecial} and {@code invokestatic}, neither of which consults
 * the subclass, so no inheritance-based AOP framework can intercept them.
 * <p>
 * 这里的每一条拒绝都会变成一次点名到类和方法的启动期失败，任何一条都不得静默跳过。
 *
 * @author wisdomme
 * @since 6.3.0
 */
public final class AopEligibility {

    /** Annotations that request interception. */
    private static final List<Class<? extends Annotation>> AOP_ANNOTATIONS =
            Collections.unmodifiableList(Arrays.asList(Transactional.class, ExceptionCatch.class));

    private AopEligibility() {
        // Utility class
    }

    /**
     * The annotations that request interception.
     * <p>
     * Exposed so that wiring code can prove every one of them is either served by an advisor or
     * explicitly declared unavailable. Without that check, an annotation nobody wired up fails
     * silently on beans that also carry an annotation that <em>is</em> wired. See issue #190.
     *
     * @return an unmodifiable view of the recognised AOP annotations
     */
    public static List<Class<? extends Annotation>> getAopAnnotations() {
        return AOP_ANNOTATIONS;
    }

    /**
     * Collects the methods of the given class that request interception.
     * <p>
     * A class-level AOP annotation applies to every declared method, matching what
     * {@code AopAdvisor.AnnotationAopAdvisor.matches} does.
     *
     * @param beanClass the class to scan
     * @return the methods requesting interception, in declaration order
     */
    public static Set<Method> findAopAnnotatedMethods(Class<?> beanClass) {
        Set<Method> result = new LinkedHashSet<>();
        if (beanClass == null) {
            return result;
        }
        for (Class<? extends Annotation> annotation : AOP_ANNOTATIONS) {
            boolean classLevel = beanClass.isAnnotationPresent(annotation);
            for (Method method : beanClass.getDeclaredMethods()) {
                if (method.isSynthetic()) {
                    continue;
                }
                if (classLevel || method.isAnnotationPresent(annotation)) {
                    result.add(method);
                }
            }
        }
        return result;
    }

    /**
     * Checks whether the given class can be proxied.
     *
     * @param beanClass        the class to check
     * @param annotatedMethods the methods requesting interception, from
     *                         {@link #findAopAnnotatedMethods(Class)}
     * @return the blocking problems, empty if the class can be proxied
     */
    public static List<Problem> check(Class<?> beanClass, Set<Method> annotatedMethods) {
        List<Problem> problems = new ArrayList<>();
        if (beanClass == null || annotatedMethods == null || annotatedMethods.isEmpty()) {
            return problems;
        }

        if (Modifier.isFinal(beanClass.getModifiers())) {
            problems.add(new Problem(Problem.Kind.FINAL_CLASS, beanClass.getName(),
                    "Remove the 'final' keyword from the class and mark it @Final instead, "
                            + "which keeps the non-extendable contract while allowing AOP. "
                            + "If the class is generated by Lombok @Value or @UtilityClass, "
                            + "switch to @Data - Lombok also emits 'final'."));
            // A final class blocks everything else; method-level findings would be noise.
            return problems;
        }

        for (Method method : annotatedMethods) {
            String location = beanClass.getName() + "#" + method.getName();
            int modifiers = method.getModifiers();
            if (Modifier.isStatic(modifiers)) {
                problems.add(new Problem(Problem.Kind.STATIC_METHOD, location,
                        "Static methods have no bean instance, so transactions and exception "
                                + "handling have nothing to apply to. Remove the AOP annotation, "
                                + "or make the method an instance method."));
            } else if (Modifier.isPrivate(modifiers)) {
                problems.add(new Problem(Problem.Kind.PRIVATE_METHOD, location,
                        "Private methods are dispatched with invokespecial and cannot be "
                                + "intercepted by any inheritance-based AOP framework. Remove the "
                                + "AOP annotation, or widen the method to package-private."));
            } else if (Modifier.isFinal(modifiers)) {
                problems.add(new Problem(Problem.Kind.FINAL_METHOD, location,
                        "Remove the 'final' keyword from the method and mark it @Final instead, "
                                + "which keeps the non-overridable contract while allowing AOP."));
            }
        }
        return problems;
    }

    /**
     * Whether an inheritance-based proxy can intercept a single method.
     * <p>
     * Shares its rules with {@link #check(Class, Set)}, which is why the two must be changed
     * together. They exist separately because they serve opposite audiences. A method-level
     * annotation is an explicit request, so an unproxyable one becomes a startup failure. A
     * class-level annotation is a bulk request the author never vetted method by method, so the
     * class-level path filters with this predicate instead of failing the whole module. See
     * issue #309.
     * <p>
     * 与 check 共用同一组规则，两者必须同步修改。分开存在是因为受众相反：方法级注解是显式点名，
     * 不可代理即启动失败；类级注解是批量覆盖，作者从未逐个过目，因此改为过滤而不是让模块加载失败。
     *
     * @param method the method to test, may be null
     * @return true if an inheritance-based proxy can intercept it
     */
    public static boolean isProxyable(Method method) {
        if (method == null) {
            return false;
        }
        int modifiers = method.getModifiers();
        return !Modifier.isStatic(modifiers)
                && !Modifier.isPrivate(modifiers)
                && !Modifier.isFinal(modifiers);
    }

    /**
     * A single reason a class cannot be proxied.
     */
    public static final class Problem {

        /** The category of the problem. */
        public enum Kind {
            /** The class itself is final and cannot be subclassed. */
            FINAL_CLASS,
            /** An annotated method is final and cannot be overridden. */
            FINAL_METHOD,
            /** An annotated method is private and cannot be intercepted. */
            PRIVATE_METHOD,
            /** An annotated method is static and has no bean instance. */
            STATIC_METHOD
        }

        private final Kind kind;
        private final String location;
        private final String remedy;

        Problem(Kind kind, String location, String remedy) {
            this.kind = kind;
            this.location = location;
            this.remedy = remedy;
        }

        /**
         * @return the category of this problem
         */
        public Kind getKind() {
            return kind;
        }

        /**
         * @return the fully qualified class name, or {@code class#method} for method-level problems
         */
        public String getLocation() {
            return location;
        }

        /**
         * @return actionable instructions for the module author
         */
        public String getRemedy() {
            return remedy;
        }

        @Override
        public String toString() {
            return kind + " at " + location + ": " + remedy;
        }
    }
}
