package com.ultikits.ultitools.aop;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.description.annotation.AnnotationDescription;
import net.bytebuddy.description.modifier.Visibility;
import net.bytebuddy.dynamic.DynamicType;
import net.bytebuddy.dynamic.loading.ClassLoadingStrategy;
import net.bytebuddy.implementation.InvocationHandlerAdapter;
import net.bytebuddy.implementation.MethodCall;
import net.bytebuddy.implementation.attribute.MethodAttributeAppender;
import net.bytebuddy.matcher.ElementMatchers;

import java.lang.annotation.Annotation;
import java.lang.reflect.InvocationHandler;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;
import java.util.concurrent.Callable;
import java.util.concurrent.ConcurrentHashMap;

import com.ultikits.ultitools.exceptions.ContainerException;
import com.ultikits.ultitools.exceptions.ErrorCode;

/**
 * Factory for creating inheritance-based subclass proxies.
 * <p>
 * The generated class is a subclass of the target whose intercepted methods delegate to the
 * {@link MethodInterceptor} chain and reach the original body through {@code super}. The
 * container instantiates the generated class directly, so the proxy <b>is</b> the bean: there is
 * no second object. This is what makes self-invocation interceptable and keeps fields, the
 * constructor count, and {@code @Autowired} injection on a single instance.
 * <p>
 * Type and method annotations are copied onto the generated class, because type annotations are
 * not {@code @Inherited} and overriding methods do not inherit method annotations. Without the
 * copy, every reflective consumer in the framework (command registration, EventBus handler
 * scanning, Bukkit's own {@code @EventHandler} scan) would silently stop seeing them.
 * <p>
 * <b>Cross-class-loader dispatch:</b> the generated class is injected into the <em>target's own</em>
 * class loader (see {@code ProxyFactoryIsolationTest}, e.g. a plugin module's URLClassLoader, which
 * is unrelated to this framework's own loader on a live Paper server). That means the intercepted
 * methods' bytecode can only reference types resolvable from the target's loader - so dispatch goes
 * through {@link InvocationHandler}, part of {@code java.base} and therefore resolvable from any
 * loader, rather than {@link net.bytebuddy.implementation.MethodDelegation}'s {@code @SuperCall}
 * binding, which would bake a hard reference to this framework-defined class into the proxy and
 * throw {@link NoClassDefFoundError} the moment the target's loader cannot see it. The super call
 * that {@code @SuperCall} would otherwise synthesize is instead generated by hand as a same-package,
 * same-signature "trampoline" method per intercepted method, invoked reflectively by name from the
 * dispatcher - see {@link #trampolineName(Method)}.
 * <p>
 * <b>Limitations</b> (surfaced as a {@link RuntimeException} naming the target class rather than a
 * bare ByteBuddy exception or a silent skip; a startup-time eligibility pre-check is planned as
 * {@link AopEligibility}):
 * <ul>
 *   <li>Cannot subclass final classes</li>
 *   <li>Cannot override final, private or static methods</li>
 *   <li>The target class must have a constructor reachable by the container</li>
 * </ul>
 *
 * @author wisdomme
 * @since 6.3.0
 */
@SuppressWarnings("PMD.AvoidAccessibilityAlteration") // AOP trampoline invocation on the generated proxy -- see 08-GATE05-TRIAGE.md
public class ProxyFactory {

    /** Prefix for the generated super-call trampoline methods; see the class javadoc. */
    private static final String TRAMPOLINE_PREFIX = "ultitools$super$";

    private final List<MethodInterceptor> interceptors;

    /**
     * Creates a new proxy factory with the given interceptors.
     *
     * @param interceptors the interceptors to apply to proxied methods
     */
    public ProxyFactory(List<MethodInterceptor> interceptors) {
        this.interceptors = interceptors;
    }

    /**
     * Checks whether the given class is a proxy generated by this factory.
     * <p>
     * Identity is read from {@link ProxyOf}, the marker this factory attaches at generation time
     * - not from a name pattern. A previous implementation matched a class-name substring and
     * silently stopped recognising proxies the moment the proxy engine changed (CGLIB to
     * ByteBuddy); reading a declared marker instead of a naming convention is what makes this
     * survive the next engine change too. Callers that need the original class must ask here
     * (or {@link #unwrap(Class)}) rather than deriving it themselves - see {@link ProxyOf}.
     *
     * @param clazz the class to test, may be null
     * @return true if the class was generated by this factory
     */
    public static boolean isProxyClass(Class<?> clazz) {
        return clazz != null && clazz.isAnnotationPresent(ProxyOf.class);
    }

    /**
     * Returns the class a generated proxy subclasses and delegates to.
     * <p>
     * Reads {@link ProxyOf} directly - no hierarchy walk. A proxy of a proxy already carries a
     * marker naming the <em>original</em> target (see {@link #createProxyClass}), so this never
     * needs to loop, and the divergent edge cases three previous unwrap implementations
     * disagreed on (proxy-of-proxy, a null superclass, whether to fall back to {@code Object.class})
     * do not exist here to reconcile.
     *
     * @param clazz the class to unwrap, may be null
     * @return the proxied target class if {@code clazz} is a proxy, {@code clazz} itself if it is
     *         not a proxy, or {@code null} if {@code clazz} is null
     */
    public static Class<?> unwrap(Class<?> clazz) {
        if (clazz == null) {
            return null;
        }
        ProxyOf marker = clazz.getAnnotation(ProxyOf.class);
        return marker != null ? marker.value() : clazz;
    }

    /**
     * Generates a proxy subclass of the given target.
     * <p>
     * Instantiation is left to the caller so that the container's existing constructor-injection
     * paths keep working: ByteBuddy copies every constructor of the target class onto the subclass.
     *
     * @param targetClass        the class to subclass
     * @param interceptedMethods the exact methods to intercept; methods outside this set keep the
     *                           original body and the original annotations. Bridge and synthetic
     *                           methods are always ignored even if present in this set - they are
     *                           compiler artifacts of implementing a generic supertype or interface
     *                           (a raw-erasure overload calling the real method), and generating a
     *                           super-call trampoline for one throws at build time
     * @param <T>                the target type
     * @return the generated subclass
     * @throws NullPointerException if {@code interceptedMethods} is null
     * @throws RuntimeException     if the proxy cannot be generated; see the class javadoc's
     *                               Limitations section
     */
    public <T> Class<? extends T> createProxyClass(Class<T> targetClass,
                                                   Set<Method> interceptedMethods) {
        Objects.requireNonNull(interceptedMethods, "interceptedMethods");

        // ByteBuddy's own method matcher already excludes synthetic methods by default, so a
        // bridge method (e.g. the raw Object overload the compiler adds alongside a generic
        // supertype's typed override) could never actually be intercepted - but
        // MethodCall.invoke(bridgeMethod).onSuper() still throws IllegalStateException at build
        // time if we try to generate a trampoline for one. Drop them up front.
        Set<Method> methodsToIntercept = new LinkedHashSet<>();
        for (Method method : interceptedMethods) {
            if (!method.isBridge() && !method.isSynthetic()) {
                methodsToIntercept.add(method);
            }
        }

        try {
            // @ProxyOf must name the *original* target, not an intermediate proxy: unwrap(targetClass)
            // returns targetClass unchanged when it is not itself a proxy, and returns the original
            // target when it is - so proxying an already-proxied class still points at the class that
            // was proxied first.
            Class<?> originalTarget = unwrap(targetClass);

            // Type annotations are not @Inherited; copy them or every class-level scan breaks. The
            // target's own @ProxyOf (present only if targetClass is itself a proxy) is filtered out
            // of the copy - otherwise proxying an already-proxied class would carry forward a stale
            // marker pointing at the intermediate proxy, alongside the fresh one added below.
            List<AnnotationDescription> typeAnnotations = new ArrayList<>();
            for (Annotation annotation : targetClass.getAnnotations()) {
                if (annotation.annotationType() != ProxyOf.class) {
                    typeAnnotations.add(AnnotationDescription.ForLoadedAnnotation.of(annotation));
                }
            }
            typeAnnotations.add(AnnotationDescription.Builder.ofType(ProxyOf.class)
                    .define("value", originalTarget)
                    .build());

            DynamicType.Builder<T> builder = new ByteBuddy()
                    .subclass(targetClass)
                    .annotateType(typeAnnotations);

            // One same-signature trampoline per intercepted method, calling straight to super.
            // This is the hand-rolled equivalent of @SuperCall's auto-generated accessor - see the
            // class javadoc for why @SuperCall itself is not an option here. Package-private
            // visibility keeps it out of the bean's public API: nothing but this factory's own
            // InterceptorDispatcher (via setAccessible) ever needs to call it, and a public
            // trampoline would let any caller bypass the interceptor chain - @Transactional,
            // @ExceptionCatch, permission checks - by calling it directly.
            for (Method method : methodsToIntercept) {
                builder = builder
                        .defineMethod(trampolineName(method), method.getReturnType(),
                                Visibility.PACKAGE_PRIVATE)
                        .withParameters(method.getParameterTypes())
                        .throwing(method.getExceptionTypes())
                        .intercept(MethodCall.invoke(method).onSuper().withAllArguments());
            }

            return builder
                    .method(ElementMatchers.anyOf(methodsToIntercept.toArray(new Method[0])))
                    .intercept(InvocationHandlerAdapter.of(new InterceptorDispatcher(interceptors)))
                    // Overriding methods do not inherit annotations; copy them for the same reason.
                    .attribute(MethodAttributeAppender.ForInstrumentedMethod.INCLUDING_RECEIVER)
                    .make()
                    .load(targetClass.getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                    .getLoaded();
        } catch (RuntimeException e) {
            // GATE-05 group two (08-21): routed to the typed container hierarchy -- the
            // generated proxy class IS the bean in this framework's design, so a failure to
            // build it is a bean-creation failure.
            throw new ContainerException(ErrorCode.BEAN_CREATION_FAILED,
                    "Failed to create a proxy for " + targetClass.getName() +
                    ". Common causes: the class is final, has no constructor reachable by the " +
                    "container, or one of the intercepted methods cannot be overridden.", e);
        }
    }

    /**
     * Deterministic trampoline name for a given method, derived purely from its own name and
     * parameter types so that {@link #createProxyClass} (build time) and
     * {@link InterceptorDispatcher} (call time, reflecting on {@code proxy.getClass()}) always agree
     * without sharing any other state.
     */
    private static String trampolineName(Method method) {
        StringBuilder name = new StringBuilder(TRAMPOLINE_PREFIX).append(method.getName());
        for (Class<?> parameterType : method.getParameterTypes()) {
            name.append('$').append(parameterType.getName()
                    .replace('.', '_').replace('[', '_').replace(';', '_'));
        }
        return name.toString();
    }

    /**
     * Dispatches intercepted calls to the {@link MethodInterceptor} chain.
     * <p>
     * Implements the bootstrap-visible {@link InvocationHandler} rather than being bound as a
     * {@link net.bytebuddy.implementation.MethodDelegation} target - see the class javadoc for why
     * a hard reference to this class in the generated proxy's bytecode is not safe to take.
     */
    private static class InterceptorDispatcher implements InvocationHandler {

        private final List<MethodInterceptor> interceptors;

        /**
         * Caches the trampoline {@link Method} per intercepted method. Safe to key on the method
         * alone: one dispatcher instance is bound to exactly one generated class (see
         * {@link #createProxyClass}), so {@code proxy.getClass()} is invariant across every call
         * this instance ever handles.
         */
        private final ConcurrentHashMap<Method, Method> trampolineCache = new ConcurrentHashMap<>();

        InterceptorDispatcher(List<MethodInterceptor> interceptors) {
            this.interceptors = interceptors;
        }

        @Override
        public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
            Object[] arguments = args != null ? args : new Object[0];

            // Resolved eagerly, before the interceptor chain is touched: a missing trampoline is a
            // ProxyFactory bug, not a target-method failure, and must not be catchable by
            // @ExceptionCatch (its default value() is {Exception.class}, which a plain
            // NoSuchMethodException would match, and silent=true would swallow it outright).
            Method trampoline = resolveTrampoline(proxy.getClass(), method);
            Callable<Object> superCall = () -> invokeTrampoline(trampoline, proxy, arguments);

            if (interceptors == null || interceptors.isEmpty()) {
                return superCall.call();
            }

            ReflectiveMethodInvocation invocation = new ReflectiveMethodInvocation(
                    proxy, method, arguments, interceptors, superCall);
            return invocation.proceed();
        }

        private Method resolveTrampoline(Class<?> proxyClass, Method method) {
            return trampolineCache.computeIfAbsent(method, m -> {
                try {
                    Method trampoline = proxyClass.getDeclaredMethod(
                            trampolineName(m), m.getParameterTypes());
                    trampoline.setAccessible(true);
                    return trampoline;
                } catch (NoSuchMethodException e) {
                    throw new IllegalStateException("BUG: ProxyFactory generated no trampoline for "
                            + "intercepted method " + m + " on " + proxyClass.getName(), e);
                }
            });
        }

        /**
         * Invokes an already-resolved trampoline, and unwraps {@link InvocationTargetException} so
         * checked exceptions reach the caller as their original type rather than wrapped - matching
         * what a direct {@code super.method()} call would have thrown. See {@link SneakyThrows} for
         * why this needs a checked-exception-safe rethrow at all, and why it is not defined here.
         */
        private static Object invokeTrampoline(Method trampoline, Object proxy, Object[] arguments)
                throws Exception {
            try {
                return trampoline.invoke(proxy, arguments);
            } catch (InvocationTargetException e) {
                throw SneakyThrows.sneakyThrow(e.getCause());
            }
        }
    }
}
