package com.ultikits.ultitools.aop;

import net.bytebuddy.ByteBuddy;
import net.bytebuddy.description.modifier.Visibility;
import net.bytebuddy.dynamic.DynamicType;
import net.bytebuddy.dynamic.loading.ClassLoadingStrategy;
import net.bytebuddy.implementation.InvocationHandlerAdapter;
import net.bytebuddy.implementation.MethodCall;
import net.bytebuddy.implementation.attribute.MethodAttributeAppender;
import net.bytebuddy.matcher.ElementMatchers;

import java.lang.reflect.InvocationHandler;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.List;
import java.util.Set;
import java.util.concurrent.Callable;

/**
 * Factory for creating inheritance-based subclass proxies.
 * <p>
 * The generated class is a subclass of the target whose intercepted methods delegate to the
 * {@link MethodInterceptor} chain and reach the original body through {@code super}. The
 * container instantiates the generated class directly, so the proxy <b>is</b> the bean: there is
 * no second object. This is what makes self-invocation interceptable and keeps fields, the
 * constructor count, and {@code @Autowired} injection on a single instance.
 * <p>
 * Type and method annotations are copied onto the generated class, because type annotations are
 * not {@code @Inherited} and overriding methods do not inherit method annotations. Without the
 * copy, every reflective consumer in the framework (command registration, EventBus handler
 * scanning, Bukkit's own {@code @EventHandler} scan) would silently stop seeing them.
 * <p>
 * <b>Cross-class-loader dispatch:</b> the generated class is injected into the <em>target's own</em>
 * class loader (see {@code ProxyFactoryIsolationTest}, e.g. a plugin module's URLClassLoader, which
 * is unrelated to this framework's own loader on a live Paper server). That means the intercepted
 * methods' bytecode can only reference types resolvable from the target's loader - so dispatch goes
 * through {@link InvocationHandler}, part of {@code java.base} and therefore resolvable from any
 * loader, rather than {@link net.bytebuddy.implementation.MethodDelegation}'s {@code @SuperCall}
 * binding, which would bake a hard reference to this framework-defined class into the proxy and
 * throw {@link NoClassDefFoundError} the moment the target's loader cannot see it. The super call
 * that {@code @SuperCall} would otherwise synthesize is instead generated by hand as a same-package,
 * same-signature "trampoline" method per intercepted method, invoked reflectively by name from the
 * dispatcher - see {@link #trampolineName(Method)}.
 * <p>
 * <b>Limitations</b> (all reported at startup rather than silently skipped, see
 * {@link AopEligibility}):
 * <ul>
 *   <li>Cannot subclass final classes</li>
 *   <li>Cannot override final, private or static methods</li>
 *   <li>The target class must have a constructor reachable by the container</li>
 * </ul>
 *
 * @author wisdomme
 * @since 6.3.0
 */
public class ProxyFactory {

    /** Infix ByteBuddy places in generated subclass names. */
    private static final String PROXY_MARKER = "$ByteBuddy$";

    /** Prefix for the generated super-call trampoline methods; see the class javadoc. */
    private static final String TRAMPOLINE_PREFIX = "ultitools$super$";

    private final List<MethodInterceptor> interceptors;

    /**
     * Creates a new proxy factory with the given interceptors.
     *
     * @param interceptors the interceptors to apply to proxied methods
     */
    public ProxyFactory(List<MethodInterceptor> interceptors) {
        this.interceptors = interceptors;
    }

    /**
     * Checks whether the given class is a proxy generated by this factory.
     * <p>
     * The naming convention is owned by this class: callers that need the original class must ask
     * here rather than pattern-matching class names themselves. A previous implementation detail
     * leaked into {@code TaskManager}, which matched CGLIB's {@code $$} infix and silently stopped
     * recognising proxies when the engine changed.
     *
     * @param clazz the class to test, may be null
     * @return true if the class was generated by this factory
     */
    public static boolean isProxyClass(Class<?> clazz) {
        return clazz != null && clazz.getName().contains(PROXY_MARKER);
    }

    /**
     * Generates a proxy subclass of the given target.
     * <p>
     * Instantiation is left to the caller so that the container's existing constructor-injection
     * paths keep working: ByteBuddy copies every constructor of the target class onto the subclass.
     *
     * @param targetClass        the class to subclass
     * @param interceptedMethods the exact methods to intercept; methods outside this set keep the
     *                           original body and the original annotations
     * @param <T>                the target type
     * @return the generated subclass
     */
    public <T> Class<? extends T> createProxyClass(Class<T> targetClass,
                                                   Set<Method> interceptedMethods) {
        DynamicType.Builder<T> builder = new ByteBuddy()
                .subclass(targetClass)
                // Type annotations are not @Inherited; copy them or every class-level scan breaks.
                .annotateType(targetClass.getAnnotations());

        // One same-signature trampoline per intercepted method, calling straight to super. This is
        // the hand-rolled equivalent of @SuperCall's auto-generated accessor - see the class javadoc
        // for why @SuperCall itself is not an option here.
        for (Method method : interceptedMethods) {
            builder = builder
                    .defineMethod(trampolineName(method), method.getReturnType(), Visibility.PUBLIC)
                    .withParameters(method.getParameterTypes())
                    .throwing(method.getExceptionTypes())
                    .intercept(MethodCall.invoke(method).onSuper().withAllArguments());
        }

        return builder
                .method(ElementMatchers.anyOf(interceptedMethods.toArray(new Method[0])))
                .intercept(InvocationHandlerAdapter.of(new InterceptorDispatcher(interceptors)))
                // Overriding methods do not inherit annotations; copy them for the same reason.
                .attribute(MethodAttributeAppender.ForInstrumentedMethod.INCLUDING_RECEIVER)
                .make()
                .load(targetClass.getClassLoader(), ClassLoadingStrategy.Default.INJECTION)
                .getLoaded();
    }

    /**
     * Deterministic trampoline name for a given method, derived purely from its own name and
     * parameter types so that {@link #createProxyClass} (build time) and
     * {@link InterceptorDispatcher} (call time, reflecting on {@code proxy.getClass()}) always agree
     * without sharing any other state.
     */
    private static String trampolineName(Method method) {
        StringBuilder name = new StringBuilder(TRAMPOLINE_PREFIX).append(method.getName());
        for (Class<?> parameterType : method.getParameterTypes()) {
            name.append('$').append(parameterType.getName()
                    .replace('.', '_').replace('[', '_').replace(';', '_'));
        }
        return name.toString();
    }

    /**
     * Dispatches intercepted calls to the {@link MethodInterceptor} chain.
     * <p>
     * Implements the bootstrap-visible {@link InvocationHandler} rather than being bound as a
     * {@link net.bytebuddy.implementation.MethodDelegation} target - see the class javadoc for why
     * a hard reference to this class in the generated proxy's bytecode is not safe to take.
     */
    private static class InterceptorDispatcher implements InvocationHandler {

        private final List<MethodInterceptor> interceptors;

        InterceptorDispatcher(List<MethodInterceptor> interceptors) {
            this.interceptors = interceptors;
        }

        @Override
        public Object invoke(Object proxy, Method method, Object[] args) throws Throwable {
            Object[] arguments = args != null ? args : new Object[0];
            Callable<Object> superCall = () -> invokeTrampoline(proxy, method, arguments);

            if (interceptors == null || interceptors.isEmpty()) {
                return superCall.call();
            }

            ReflectiveMethodInvocation invocation = new ReflectiveMethodInvocation(
                    proxy, method, arguments, interceptors, superCall);
            return invocation.proceed();
        }

        /**
         * Invokes the trampoline that {@link #createProxyClass} generated for {@code method}, and
         * unwraps {@link InvocationTargetException} so checked exceptions reach the caller as their
         * original type rather than wrapped - matching what a direct {@code super.method()} call
         * would have thrown.
         */
        private static Object invokeTrampoline(Object proxy, Method method, Object[] arguments)
                throws Exception {
            Method trampoline = proxy.getClass()
                    .getDeclaredMethod(trampolineName(method), method.getParameterTypes());
            trampoline.setAccessible(true);
            try {
                return trampoline.invoke(proxy, arguments);
            } catch (InvocationTargetException e) {
                throw sneakyThrow(e.getCause());
            }
        }

        @SuppressWarnings("unchecked")
        private static <E extends Throwable> RuntimeException sneakyThrow(Throwable t) throws E {
            throw (E) t;
        }
    }
}
